include: package:pedantic_mono/analysis_options.yaml

linter:
    rules:

analyzer:
    exclude:
        - "lib/model/state.freezed.dart"
        - "lib/model/state.*.dart"

    errors:
        always_put_control_body_on_new_line: ignore
        avoid_slow_async_io: ignore
